package me.yuuki.todoapp.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table task_t
 */
public class TaskEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_t.id
     *
     * 
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_t.done
     *
     * 
     */
    private Boolean done;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_t.priority
     *
     * 
     */
    private String priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_t.start_date
     *
     * 
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_t.end_date
     *
     * 
     */
    private Date endDate;

    /**
     * Database Column Remarks:
     *   除是否完成，优先级，时间之外的东西，其中KVTag需要另外存储
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_t.task_description
     *
     * 
     */
    private String taskDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_t.user_id
     *
     * 
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_t.id
     *
     * @return the value of task_t.id
     *
     * 
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_t.id
     *
     * @param id the value for task_t.id
     *
     * 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_t.done
     *
     * @return the value of task_t.done
     *
     * 
     */
    public Boolean getDone() {
        return done;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_t.done
     *
     * @param done the value for task_t.done
     *
     * 
     */
    public void setDone(Boolean done) {
        this.done = done;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_t.priority
     *
     * @return the value of task_t.priority
     *
     * 
     */
    public String getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_t.priority
     *
     * @param priority the value for task_t.priority
     *
     * 
     */
    public void setPriority(String priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_t.start_date
     *
     * @return the value of task_t.start_date
     *
     * 
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_t.start_date
     *
     * @param startDate the value for task_t.start_date
     *
     * 
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_t.end_date
     *
     * @return the value of task_t.end_date
     *
     * 
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_t.end_date
     *
     * @param endDate the value for task_t.end_date
     *
     * 
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_t.task_description
     *
     * @return the value of task_t.task_description
     *
     * 
     */
    public String getTaskDescription() {
        return taskDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_t.task_description
     *
     * @param taskDescription the value for task_t.task_description
     *
     * 
     */
    public void setTaskDescription(String taskDescription) {
        this.taskDescription = taskDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_t.user_id
     *
     * @return the value of task_t.user_id
     *
     * 
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_t.user_id
     *
     * @param userId the value for task_t.user_id
     *
     * 
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}