package me.yuuki.todoapp.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table task_tag_t
 */
public class TaskTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_tag_t.id
     *
     * 
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   tag的类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_tag_t.type
     *
     * 
     */
    private String type;

    /**
     * Database Column Remarks:
     *   整个 tag 的值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_tag_t.value
     *
     * 
     */
    private String value;

    /**
     * Database Column Remarks:
     *   tag对应的task
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_tag_t.task_id
     *
     * 
     */
    private Integer taskId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_tag_t.id
     *
     * @return the value of task_tag_t.id
     *
     * 
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_tag_t.id
     *
     * @param id the value for task_tag_t.id
     *
     * 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_tag_t.type
     *
     * @return the value of task_tag_t.type
     *
     * 
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_tag_t.type
     *
     * @param type the value for task_tag_t.type
     *
     * 
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_tag_t.value
     *
     * @return the value of task_tag_t.value
     *
     * 
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_tag_t.value
     *
     * @param value the value for task_tag_t.value
     *
     * 
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_tag_t.task_id
     *
     * @return the value of task_tag_t.task_id
     *
     * 
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_tag_t.task_id
     *
     * @param taskId the value for task_tag_t.task_id
     *
     * 
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }
}