package me.yuuki.todoapp.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_t
 */
public class User {
    /**
     * Database Column Remarks:
     *   用户ID，登录用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_t.user_id
     *
     * 
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   用户展示的ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_t.username
     *
     * 
     */
    private String username;

    /**
     * Database Column Remarks:
     *   用户密码，需加密
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_t.passwd
     *
     * 
     */
    private String passwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_t.user_id
     *
     * @return the value of user_t.user_id
     *
     * 
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_t.user_id
     *
     * @param userId the value for user_t.user_id
     *
     * 
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_t.username
     *
     * @return the value of user_t.username
     *
     * 
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_t.username
     *
     * @param username the value for user_t.username
     *
     * 
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_t.passwd
     *
     * @return the value of user_t.passwd
     *
     * 
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_t.passwd
     *
     * @param passwd the value for user_t.passwd
     *
     * 
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
}