package me.yuuki.todoapp.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_t
 */
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_t.user_id
     *

     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   用户的邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_t.email
     *

     */
    private String email;

    /**
     * Database Column Remarks:
     *   用户密码，需加密
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_t.passwd
     *

     */
    private String passwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_t.user_id
     *
     * @return the value of user_t.user_id
     *

     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_t.user_id
     *
     * @param userId the value for user_t.user_id
     *

     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_t.email
     *
     * @return the value of user_t.email
     *

     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_t.email
     *
     * @param email the value for user_t.email
     *

     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_t.passwd
     *
     * @return the value of user_t.passwd
     *

     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_t.passwd
     *
     * @param passwd the value for user_t.passwd
     *

     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
}