package me.yuuki.todoapp.mapper;

import java.util.List;
import me.yuuki.todoapp.entity.TaskTag;
import me.yuuki.todoapp.entity.TaskTagExample;
import org.apache.ibatis.annotations.Param;

public interface TaskTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_tag_t
     *
     * @mbg.generated
     */
    long countByExample(TaskTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_tag_t
     *
     * @mbg.generated
     */
    int deleteByExample(TaskTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_tag_t
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_tag_t
     *
     * @mbg.generated
     */
    int insert(TaskTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_tag_t
     *
     * @mbg.generated
     */
    int insertSelective(TaskTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_tag_t
     *
     * @mbg.generated
     */
    List<TaskTag> selectByExample(TaskTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_tag_t
     *
     * @mbg.generated
     */
    TaskTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_tag_t
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskTag record, @Param("example") TaskTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_tag_t
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskTag record, @Param("example") TaskTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_tag_t
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaskTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_tag_t
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskTag record);
}